FROM golang:1.14.13-buster AS builder

WORKDIR /go/src/app

# Create folder structure
RUN mkdir -p bin/
RUN mkdir -p logs/

# Install dependencies
COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum
RUN go mod download

# Copy source code
COPY ./cmd ./cmd
COPY ./config ./config
COPY ./internal ./internal
COPY ./pkg ./pkg
COPY ./scripts /app/scripts
COPY ./swaggerui /app/swaggerui

CMD ["go", "test", "-count=1", "./..."]
